version: "3.8"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "test123"
      POSTGRES_DB: "test_db"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapp:
    build: .
    command: bash -c "flask db upgrade && gunicorn manage:app -b 0.0.0.0:5000 --timeout 30 --log-level=DEBUG --reload"
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    links:
      - postgres_db
    volumes:
      - .:/app

  redis:
    container_name: redis
    image: redis:6.2
    hostname: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    hostname: worker
    command: celery -A app.celery_app worker -l info
    volumes:
      - .:/app
    links:
      - postgres_db
      - redis
    depends_on:
      - postgres_db
      - redis
